"""Build VERIFY_AGAINST_SOURCE.md — a by-hand checklist for testing our answers
against othelloclub's own verdicts.

Why by hand: their board page is served behind a Google reCAPTCHA challenge, so
the site is explicitly refusing automated access to exactly the endpoint that
would tell us whether a move wins. We don't work around that. This script emits
one row per imported puzzle — the site's own link, our answer, our exact margin,
and every losing alternative — so a person can click through and check in a
couple of minutes.

Note what such a check can and cannot establish: the site judges win/lose, while
we claim the exact final disc margin under optimal play by both sides. It can
falsify our sign; it cannot confirm our margin. For that, diff against an
independent solver.

Run (from games/othello):
    python verify_against_source.py
"""

from __future__ import annotations

from pathlib import Path

import engine as E
import solver as S

SOURCE = Path("othelloclub_puzzles.txt")
OUT = Path("VERIFY_AGAINST_SOURCE.md")

HEADER = """# Checking our solutions against othelloclub's own answers

Their board page is behind a Google reCAPTCHA challenge, so this cannot be
scripted — it has to be a person clicking through in a normal browser. Each
row below is one puzzle: open the link, play the move in **our answer**, and
the site should tell you that you won.

Notes on reading this table:

- `their side` is who moves in the site's own version. For `White`, we
  colour-flipped on import so the participant is always Black; the SQUARE is
  unchanged, so play our answer as White there.
- `margin` is our exact predicted final disc difference for the side to move.
  The site only judges win/lose, so a match confirms the sign, not the margin.
- Every other legal move loses in all 20 puzzles, so playing one of the
  `alternatives` is an equally valid check in the opposite direction: the site
  should say you lost.

| date | their side | our answer | margin | alternatives (all lose) | link |
|---|---|---|---|---|---|"""

FOOTER = """
Generated by `python verify_against_source.py` (this file is its output).

## Why this is a weaker check than an engine diff

The site's task is "win from here", so its verdict is win/lose. Our claim is
the exact final disc margin under optimal play by both sides, which is
strictly stronger — the site can falsify our sign but never confirm our
margin. It also plays its own defence, which need not be the optimal defence
our tables assume, so a line can diverge from ours and still end in a win.
For real external agreement, diff against an independent solver (Edax)."""


def main() -> None:
    lines = [HEADER]
    for raw in SOURCE.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        date, turn, board_string = (x.strip() for x in line.split("|"))
        turn = int(turn)
        board, _ = E.parse_board(board_string)
        if turn == 2:            # colour-flipped on import; the squares don't move
            board = E.flip_colors(board)

        memo: dict = {}
        values = S.move_values(board, E.BLACK, memo)
        best = [E.to_notation(m) for m in S.best_moves(board, E.BLACK, memo)]
        ranked = sorted(values.items(), key=lambda kv: -kv[1])
        alternatives = ", ".join(f"{E.to_notation(m)} ({v:+d})" for m, v in ranked
                                 if E.to_notation(m) not in best)
        url = (f"https://othelloclub.com/en/board.php?board={board_string}"
               f"&turn={turn}&date={date}")
        lines.append(f"| {date} | {'Black' if turn == 1 else 'White'} | "
                     f"**{', '.join(best)}** | {max(values.values()):+d} | "
                     f"{alternatives} | [open]({url}) |")
    lines.append(FOOTER)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(lines) - 2} puzzles)")


if __name__ == "__main__":
    main()
